# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\"\x16\n\x06ReqMsg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"F\n\ntable_pkts\x12\r\n\x05scrip\x18\x01 \x01(\t\x12\x1b\n\x13request_pkts_amount\x18\x02 \x01(\r\x12\x0c\n\x04rate\x18\x03 \x01(\r\"W\n\x11grpc_dpdk_arp_res\x12\x1d\n\x08\x61rp_pkts\x18\x01 \x03(\x0b\x32\x0b.table_pkts\x12#\n\x0emulticast_pkts\x18\x02 \x03(\x0b\x32\x0b.table_pkts22\n\x07Greeter\x12\'\n\x06GetMsg\x12\x07.ReqMsg\x1a\x12.grpc_dpdk_arp_res\"\x00\x62\x06proto3')



_REQMSG = DESCRIPTOR.message_types_by_name['ReqMsg']
_TABLE_PKTS = DESCRIPTOR.message_types_by_name['table_pkts']
_GRPC_DPDK_ARP_RES = DESCRIPTOR.message_types_by_name['grpc_dpdk_arp_res']
ReqMsg = _reflection.GeneratedProtocolMessageType('ReqMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQMSG,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:ReqMsg)
  })
_sym_db.RegisterMessage(ReqMsg)

table_pkts = _reflection.GeneratedProtocolMessageType('table_pkts', (_message.Message,), {
  'DESCRIPTOR' : _TABLE_PKTS,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:table_pkts)
  })
_sym_db.RegisterMessage(table_pkts)

grpc_dpdk_arp_res = _reflection.GeneratedProtocolMessageType('grpc_dpdk_arp_res', (_message.Message,), {
  'DESCRIPTOR' : _GRPC_DPDK_ARP_RES,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:grpc_dpdk_arp_res)
  })
_sym_db.RegisterMessage(grpc_dpdk_arp_res)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQMSG._serialized_start=14
  _REQMSG._serialized_end=36
  _TABLE_PKTS._serialized_start=38
  _TABLE_PKTS._serialized_end=108
  _GRPC_DPDK_ARP_RES._serialized_start=110
  _GRPC_DPDK_ARP_RES._serialized_end=197
  _GREETER._serialized_start=199
  _GREETER._serialized_end=249
# @@protoc_insertion_point(module_scope)
