/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: grpc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "grpc.pb-c.h"
void   arp_common_res__init
                     (ArpCommonRes         *message)
{
  static const ArpCommonRes init_value = ARP_COMMON_RES__INIT;
  *message = init_value;
}
size_t arp_common_res__get_packed_size
                     (const ArpCommonRes *message)
{
  assert(message->base.descriptor == &arp_common_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t arp_common_res__pack
                     (const ArpCommonRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &arp_common_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t arp_common_res__pack_to_buffer
                     (const ArpCommonRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &arp_common_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ArpCommonRes *
       arp_common_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ArpCommonRes *)
     protobuf_c_message_unpack (&arp_common_res__descriptor,
                                allocator, len, data);
}
void   arp_common_res__free_unpacked
                     (ArpCommonRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &arp_common_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   grpc_dpdk_arp_req__init
                     (GrpcDpdkArpReq         *message)
{
  static const GrpcDpdkArpReq init_value = GRPC_DPDK_ARP_REQ__INIT;
  *message = init_value;
}
size_t grpc_dpdk_arp_req__get_packed_size
                     (const GrpcDpdkArpReq *message)
{
  assert(message->base.descriptor == &grpc_dpdk_arp_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t grpc_dpdk_arp_req__pack
                     (const GrpcDpdkArpReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &grpc_dpdk_arp_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t grpc_dpdk_arp_req__pack_to_buffer
                     (const GrpcDpdkArpReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &grpc_dpdk_arp_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GrpcDpdkArpReq *
       grpc_dpdk_arp_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GrpcDpdkArpReq *)
     protobuf_c_message_unpack (&grpc_dpdk_arp_req__descriptor,
                                allocator, len, data);
}
void   grpc_dpdk_arp_req__free_unpacked
                     (GrpcDpdkArpReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &grpc_dpdk_arp_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   grpc_dpdk_arp_res__table_pkts__init
                     (GrpcDpdkArpRes__TablePkts         *message)
{
  static const GrpcDpdkArpRes__TablePkts init_value = GRPC_DPDK_ARP_RES__TABLE_PKTS__INIT;
  *message = init_value;
}
void   grpc_dpdk_arp_res__init
                     (GrpcDpdkArpRes         *message)
{
  static const GrpcDpdkArpRes init_value = GRPC_DPDK_ARP_RES__INIT;
  *message = init_value;
}
size_t grpc_dpdk_arp_res__get_packed_size
                     (const GrpcDpdkArpRes *message)
{
  assert(message->base.descriptor == &grpc_dpdk_arp_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t grpc_dpdk_arp_res__pack
                     (const GrpcDpdkArpRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &grpc_dpdk_arp_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t grpc_dpdk_arp_res__pack_to_buffer
                     (const GrpcDpdkArpRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &grpc_dpdk_arp_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GrpcDpdkArpRes *
       grpc_dpdk_arp_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GrpcDpdkArpRes *)
     protobuf_c_message_unpack (&grpc_dpdk_arp_res__descriptor,
                                allocator, len, data);
}
void   grpc_dpdk_arp_res__free_unpacked
                     (GrpcDpdkArpRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &grpc_dpdk_arp_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor arp_common_res__field_descriptors[1] =
{
  {
    "ret_state",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ArpCommonRes, ret_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned arp_common_res__field_indices_by_name[] = {
  0,   /* field[0] = ret_state */
};
static const ProtobufCIntRange arp_common_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor arp_common_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "arp_common_res",
  "ArpCommonRes",
  "ArpCommonRes",
  "",
  sizeof(ArpCommonRes),
  1,
  arp_common_res__field_descriptors,
  arp_common_res__field_indices_by_name,
  1,  arp_common_res__number_ranges,
  (ProtobufCMessageInit) arp_common_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define grpc_dpdk_arp_req__field_descriptors NULL
#define grpc_dpdk_arp_req__field_indices_by_name NULL
#define grpc_dpdk_arp_req__number_ranges NULL
const ProtobufCMessageDescriptor grpc_dpdk_arp_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grpc_dpdk_arp_req",
  "GrpcDpdkArpReq",
  "GrpcDpdkArpReq",
  "",
  sizeof(GrpcDpdkArpReq),
  0,
  grpc_dpdk_arp_req__field_descriptors,
  grpc_dpdk_arp_req__field_indices_by_name,
  0,  grpc_dpdk_arp_req__number_ranges,
  (ProtobufCMessageInit) grpc_dpdk_arp_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor grpc_dpdk_arp_res__table_pkts__field_descriptors[3] =
{
  {
    "scrip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GrpcDpdkArpRes__TablePkts, scrip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_pkts_amount",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GrpcDpdkArpRes__TablePkts, request_pkts_amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GrpcDpdkArpRes__TablePkts, rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned grpc_dpdk_arp_res__table_pkts__field_indices_by_name[] = {
  2,   /* field[2] = rate */
  1,   /* field[1] = request_pkts_amount */
  0,   /* field[0] = scrip */
};
static const ProtobufCIntRange grpc_dpdk_arp_res__table_pkts__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor grpc_dpdk_arp_res__table_pkts__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grpc_dpdk_arp_res.table_pkts",
  "TablePkts",
  "GrpcDpdkArpRes__TablePkts",
  "",
  sizeof(GrpcDpdkArpRes__TablePkts),
  3,
  grpc_dpdk_arp_res__table_pkts__field_descriptors,
  grpc_dpdk_arp_res__table_pkts__field_indices_by_name,
  1,  grpc_dpdk_arp_res__table_pkts__number_ranges,
  (ProtobufCMessageInit) grpc_dpdk_arp_res__table_pkts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor grpc_dpdk_arp_res__field_descriptors[3] =
{
  {
    "res",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GrpcDpdkArpRes, res),
    &arp_common_res__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arp_pkts",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GrpcDpdkArpRes, n_arp_pkts),
    offsetof(GrpcDpdkArpRes, arp_pkts),
    &grpc_dpdk_arp_res__table_pkts__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multicast_pkts",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GrpcDpdkArpRes, n_multicast_pkts),
    offsetof(GrpcDpdkArpRes, multicast_pkts),
    &grpc_dpdk_arp_res__table_pkts__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned grpc_dpdk_arp_res__field_indices_by_name[] = {
  1,   /* field[1] = arp_pkts */
  2,   /* field[2] = multicast_pkts */
  0,   /* field[0] = res */
};
static const ProtobufCIntRange grpc_dpdk_arp_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor grpc_dpdk_arp_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grpc_dpdk_arp_res",
  "GrpcDpdkArpRes",
  "GrpcDpdkArpRes",
  "",
  sizeof(GrpcDpdkArpRes),
  3,
  grpc_dpdk_arp_res__field_descriptors,
  grpc_dpdk_arp_res__field_indices_by_name,
  1,  grpc_dpdk_arp_res__number_ranges,
  (ProtobufCMessageInit) grpc_dpdk_arp_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
