// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ns.proto

#include "ns.pb.h"
#include "ns.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ns {

static const char* NetStats_method_names[] = {
  "/ns.NetStats/GetNetStats",
};

std::unique_ptr< NetStats::Stub> NetStats::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NetStats::Stub> stub(new NetStats::Stub(channel));
  return stub;
}

NetStats::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetNetStats_(NetStats_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NetStats::Stub::GetNetStats(::grpc::ClientContext* context, const ::ns::Request& request, ::ns::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetNetStats_, context, request, response);
}

void NetStats::Stub::experimental_async::GetNetStats(::grpc::ClientContext* context, const ::ns::Request* request, ::ns::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetNetStats_, context, request, response, std::move(f));
}

void NetStats::Stub::experimental_async::GetNetStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ns::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetNetStats_, context, request, response, std::move(f));
}

void NetStats::Stub::experimental_async::GetNetStats(::grpc::ClientContext* context, const ::ns::Request* request, ::ns::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetNetStats_, context, request, response, reactor);
}

void NetStats::Stub::experimental_async::GetNetStats(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ns::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetNetStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ns::Response>* NetStats::Stub::AsyncGetNetStatsRaw(::grpc::ClientContext* context, const ::ns::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::ns::Response>::Create(channel_.get(), cq, rpcmethod_GetNetStats_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ns::Response>* NetStats::Stub::PrepareAsyncGetNetStatsRaw(::grpc::ClientContext* context, const ::ns::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::ns::Response>::Create(channel_.get(), cq, rpcmethod_GetNetStats_, context, request, false);
}

NetStats::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NetStats_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NetStats::Service, ::ns::Request, ::ns::Response>(
          [](NetStats::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::ns::Request* req,
             ::ns::Response* resp) {
               return service->GetNetStats(ctx, req, resp);
             }, this)));
}

NetStats::Service::~Service() {
}

::grpc::Status NetStats::Service::GetNetStats(::grpc::ServerContext* context, const ::ns::Request* request, ::ns::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ns

